module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/KnL0Ft6gvHDGP2lH3oN5Z5?mode=wwt',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/a0mj3n.jpg',
    NEWSLETTER_JID: '120363421104812135@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝚃𝙴𝙳𝙳𝚈-𝚇𝙼𝙳',
    OWNER_NAME: '𝚃𝙴𝙳𝙳𝚈',
    OWNER_NUMBER: '254799963583',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © ᴘᴏᴡᴇʀᴇᴅ ʙʏ 𝚃𝙴𝙳𝙳𝚈-𝚃𝙴𝙲𝙷',
    CHANNEL_LINK: "https://whatsapp.com/channel/0029Vb6NveDBPzjPa4vIRt3n",
};
